### ISSUE TITLE
Links between nodes disappear after upgrade to 3.0 under Safari

### ISSUE THREAD

**Issue by luzik** [node-red/node-red#3778]
### Current Behavior

All links between nodes are gone after upgrade. In Chromium everything is working fine, errors only in Safari

```
[Log] JQMIGRATE: Migrate is installed, version 3.3.0 (vendor.js, line 4)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (purify.min.js.map, line 0)
[Log] Node-RED: 3.0.0 (red.min.js, line 16)
[Log] Versions (red.min.js, line 16)
[Log] jQuery – "3.5.1" (red.min.js, line 16)
[Log] jQuery UI – "1.12.1" (red.min.js, line 16)
[Log] ACE – "1.4.12" (red.min.js, line 16)
[Log] MONACO – "0.33.0" (red.min.js, line 16)
[Log] D3 – "3.0.3" (red.min.js, line 16)
[Log] Projects disabled (red.min.js, line 16)
[Error] TypeError: Object.hasOwn is not a function. (In 'Object.hasOwn(RED.runtime,"started")', 'Object.hasOwn' is undefined)
	(anonimowa funkcja) (red.min.js:18:367295)
	(anonimowa funkcja) (vendor.js:37:9365)
	Tn (vendor.js:35:8232)
	(anonimowa funkcja) (vendor.js:37:9337)
	Gt (red.min.js:18:360913)
```

### Steps To Reproduce

Upgrade node-red to 3.0 and use Safari

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0
- Node.js version: docker image
- npm version: docker image
- Platform/OS: Linux/docker
- Browser: Safari/macosx

**Comment by knolleary** [comment]
What version of safari are you using? This error suggests you're using using an old unsupported version.

**Comment by luzik** [comment]
It is 15.3

**Comment by Steve-Mcl** [comment]
Others on the forum have also noted this & updated Safari to 15.5 solves the issue. 

However, thanks for reporting this - it seems Safari 15.3 doesn't support `hasOwn` which we may look at ways around it.
