### ISSUE TITLE
node-red-contrib-modbus doesn't work with Node-RED v1.0.x anymore

### ISSUE THREAD

**Issue by palstek** [node-red/node-red#2317]
### What are the steps to reproduce?

Use node-red-contrib-modbus to read some registers via modbus.
`npm install -g --unsafe-perm node-red-contrib-modbus`

### What happens?

Console shows the following error when Modbus-Read Node runs:
```
(node:1) UnhandledPromiseRejectionWarning: TypeError: a is not a function
    at activateSending (/usr/lib/node_modules/node-red-contrib-modbus/modbus/maps/modbus-client.js:571:20)
```
### What do you expect to happen?

That it runs as it did with Node-RED v0.20.7.
https://discourse.nodered.org/t/node-red-1-0-0-beta-4-released/15577/7 seems to show a similar issue.

### Please tell us about your environment:

- [x] Node-RED version: v1.0.1
- [x] Node.js version: v10.16.3
- [x] npm version: 6.9.0
- [x] Platform/OS: Linux 4.9.0-11-amd64 x64 LE
- [ ] Browser:

**Comment by hardillb** [comment]
So raise this with the owner of that module

**Comment by knolleary** [comment]
Please raise an issue against node-red-contrib-modbus. This repo is for the core of Node-RED, not third party nodes.

**Comment by palstek** [comment]
Sorry.
I found the corresponding issue there: https://github.com/BiancoRoyal/node-red-contrib-modbus/issues/144
