### ISSUE TITLE
Join node creates exception in Node Red 5.0.2

### ISSUE THREAD

**Issue by friebi** [node-red/node-red#5887]
### Current Behavior

Join node creates an exception with Node Red 5.0.2.

```
name: "TypeError"
message: "property.hasOwnProperty is not a function"
stack: string

TypeError: property.hasOwnProperty is not a function
    at JoinNode._inputCallback (/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/core/sequence/17-split.js:770:42)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:214:26
    at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:206:11)
    at Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:190:25)
    at Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:506:10)
    at deliverMessageToDestination (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:824:40)
    at Immediate._onImmediate (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:840:21)
    at process.processImmediate (node:internal/timers:504:21)
```

Reverting to Node Red 5.0.1 fixes the issue.

### Expected Behavior

No exception.

### Steps To Reproduce

Update to Node Red 5.0.2 and use join node.

### Environment

- Node-RED version: 5.0.2
- Node.js version: v24.18.1
- npm version: 11.16.0
- Platform/OS: DietPi 10.5.2
- Browser: Firefox

**Comment by hardillb** [comment]
Hi,

1. Did this work with 5.0.0 or 5.0.1?
2. Can you please try and build a small example flow that shows the problem please

**Comment by colinl** [comment]
I am not seeing any problem with Join nodes, it must be a particular use case that is causing it for you.  Can you post a simple flow with just inject nodes and a join that shows the problem please.

**Comment by friebi** [comment]
Thanks for the fast replies 😄 
1. yes, it works since a long time including 5.0.0 and 5.0.1
1. I will try to provide a minimal example tomorrow 👍

**Comment by knolleary** [comment]
Just to note, I'm going to be offline for 10 days from tomorrow, so won't be able to publish a fix if one is needed. If you're able to provide any more information about your flow *tonight* there is a small chance I can do something.

**Comment by hardillb** [comment]
But there has been no change between 5.0.1 and 5.0.2 in the join node that I can see

https://github.com/node-red/node-red/compare/5.0.1...5.0.2

**Comment by friebi** [comment]
> But there has been no change between 5.0.1 and 5.0.2 in the join node that I can see
> 
> [5.0.1...5.0.2](https://github.com/node-red/node-red/compare/5.0.1...5.0.2)

I was also checking the changes and did see no direct change.
I am trying to update to 5.0.2 now and see if the issue re-appears.

**Comment by friebi** [comment]
> Just to note, I'm going to be offline for 10 days from tomorrow, so won't be able to publish a fix if one is needed. If you're able to provide any more information about your flow _tonight_ there is a small chance I can do something.

Thank you so much for your effort, you really do not need to hurry because of me. I can wait 😄 

The issue re-occurs after updating to 5.0.2.

<details>
<summary>Here is a minimal flow to reproduce it</summary>

```
[
    {
        "id": "e8e25a4728adaf92",
        "type": "inject",
        "z": "a9df06bc.3525e",
        "name": "",
        "props": [
            {
                "p": "time",
                "v": "",
                "vt": "date"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 430,
        "y": 2180,
        "wires": [
            [
                "747719f5a49474e7",
                "c556c188d553e867"
            ]
        ]
    },
    {
        "id": "b04313eae2cf619c",
        "type": "join",
        "z": "a9df06bc.3525e",
        "name": "",
        "mode": "custom",
        "build": "merged",
        "property": "payload",
        "propertyType": "msg",
        "key": "topic",
        "joiner": "\\n",
        "joinerType": "str",
        "useparts": false,
        "accumulate": false,
        "timeout": "1",
        "count": "",
        "reduceRight": false,
        "reduceExp": "",
        "reduceInit": "",
        "reduceInitType": "",
        "reduceFixup": "",
        "x": 830,
        "y": 2180,
        "wires": [
            [
                "28ded04e2f68fd84"
            ]
        ]
    },
    {
        "id": "747719f5a49474e7",
        "type": "change",
        "z": "a9df06bc.3525e",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"a\": 1, \"time\": time}",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 640,
        "y": 2160,
        "wires": [
            [
                "b04313eae2cf619c"
            ]
        ]
    },
    {
        "id": "c556c188d553e867",
        "type": "change",
        "z": "a9df06bc.3525e",
        "name": "",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "{\"b\": 2, \"time\": time}",
                "tot": "jsonata"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 640,
        "y": 2200,
        "wires": [
            [
                "b04313eae2cf619c"
            ]
        ]
    },
    {
        "id": "28ded04e2f68fd84",
        "type": "debug",
        "z": "a9df06bc.3525e",
        "name": "debug 1",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 980,
        "y": 2180,
        "wires": []
    }
]
```

</details>

**Comment by colinl** [comment]
I can confirm that the problem is repeatable.  In fact it is only necessary to send in one message to get the error immediately. The second change node can be removed.

**Comment by knolleary** [comment]
Is the jsonata expression relevant? There was a minor version update to the jsonata we include.

**Comment by hardillb** [comment]
I think the JSONATA is returning objects that have no prototype functions, I stuck a console.log in just before the failure and it's showing the object has a null prototype

```
BEN [Object: null prototype] { a: 1 } object
undefined
30 Jul 21:38:22 - [error] [join:b04313eae2cf619c] TypeError: property.hasOwnProperty is not a function
TypeError: property.hasOwnProperty is not a function
    at JoinNode._inputCallback (/opt/share/playing/node-red/node-red/packages/node_modules/@node-red/nodes/core/sequence/17-split.js:772:42)
    at /opt/share/playing/node-red/node-red/packages/node_modules/@node-red/runtime/lib/nodes/Node.js:214:26
    at Object.trigger (/opt/share/playing/node-red/node-red/packages/node_modules/@node-red/util/lib/hooks.js:166:13)
    at Node._emitInput (/opt/share/playing/node-red/node-red/packages/node_modules/@node-red/runtime/lib/nodes/Node.js:206:11)
    at Node.emit (/opt/share/playing/node-red/node-red/packages/node_modules/@node-red/runtime/lib/nodes/Node.js:190:25)
    at Node.receive (/opt/share/playing/node-red/node-red/packages/node_modules/@node-red/runtime/lib/nodes/Node.js:506:10)
    at deliverMessageToDestination (/opt/share/playing/node-red/node-red/packages/node_modules/@node-red/runtime/lib/flows/Flow.js:824:40)
    at Immediate._onImmediate (/opt/share/playing/node-red/node-red/packages/node_modules/@node-red/runtime/lib/flows/Flow.js:840:21)
    at process.processImmediate (node:internal/timers:505:21)
```

```
                    } else {
                        for (propertyKey in property) {
                            console.log('BEN', property, typeof property)
                            console.log(typeof property.hasOwnProperty)
                            if (property.hasOwnProperty(propertyKey) && propertyKey !== '_msgid') {
                                group.payload[propertyKey] = property[propertyKey];
                            }
                        }
                        group.currentCount = Object.keys(group.payload).length;
                        //group.currentCount++;
                    }
```

**Comment by colinl** [comment]
It does seem to be the JSONata that is causing the problem. Removing the `time` property from the jsonata makes no difference, but switching to {} removes the problem, even though the message looks identical.

**Comment by hardillb** [comment]
Quick and dirty fix

```
                    } else {
                        for (propertyKey in property) {
                            console.log('BEN', property, typeof property)
                            property = {...property}  // <-- HERE
                            if (property.hasOwnProperty(propertyKey) && propertyKey !== '_msgid') {
                                group.payload[propertyKey] = property[propertyKey];
                            }
                        }
                        group.currentCount = Object.keys(group.payload).length;
                        //group.currentCount++;
                    }
```

**Comment by hardillb** [comment]
But that only fixes join node, it feels like a JSONATA problem that could hit other node downstream

**Comment by knolleary** [comment]
Looking at reverting the JSONata update....

**Comment by knolleary** [comment]
https://github.com/jsonata-js/jsonata/issues/811

**Comment by knolleary** [comment]
Confirmed this is a change between 2.2.1 and 2.2.2

I have logged upstream via https://github.com/jsonata-js/jsonata/issues/827

I will run a maintenance release now that reverts back to 2.1.1 - the version we had in 5.0.1. I'm not going to risk only going back to 2.2.1 (even though that doesn't have *this* issue) in case there are other hidden issues waiting to be found.

**Comment by hardillb** [comment]
Will do a point release for stacks in the morning (day job thing...)

**Comment by knolleary** [comment]
Sorry - we had 2.2.1 in 5.0.0/.1 - so I will go back to that one.

**Comment by knolleary** [comment]
5.0.4 now published with JSONata reverted to 2.0.6.

Ignore the 5.0.3 release... turns out I was wrong about 2.2.1 being okay.

**Comment by friebi** [comment]
5.0.4 works fine on my side.
Thanks a lot! You are awesome!
