### PR TITLE
Remove use of Object.hasOwn

### LINKED ISSUE #3778: Links between nodes disappear after upgrade to 3.0 under Safari
### Current Behavior

All links between nodes are gone after upgrade. In Chromium everything is working fine, errors only in Safari

```
[Log] JQMIGRATE: Migrate is installed, version 3.3.0 (vendor.js, line 4)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (purify.min.js.map, line 0)
[Log] Node-RED: 3.0.0 (red.min.js, line 16)
[Log] Versions (red.min.js, line 16)
[Log] jQuery – "3.5.1" (red.min.js, line 16)
[Log] jQuery UI – "1.12.1" (red.min.js, line 16)
[Log] ACE – "1.4.12" (red.min.js, line 16)
[Log] MONACO – "0.33.0" (red.min.js, line 16)
[Log] D3 – "3.0.3" (red.min.js, line 16)
[Log] Projects disabled (red.min.js, line 16)
[Error] TypeError: Object.hasOwn is not a function. (In 'Object.hasOwn(RED.runtime,"started")', 'Object.hasOwn' is undefined)
	(anonimowa funkcja) (red.min.js:18:367295)
	(anonimowa funkcja) (vendor.js:37:9365)
	Tn (vendor.js:35:8232)
	(anonimowa funkcja) (vendor.js:37:9337)
	Gt (red.min.js:18:360913)
```

### Expected Behavior

_No response_

### Steps To Reproduce

Upgrade node-red to 3.0 and use Safari

### Example flow

```
paste your flow here
```

### Environment

- Node-RED version: 3.0
- Node.js version: docker image
- npm version: docker image
- Platform/OS: Linux/docker
- Browser: Safari/macosx

### PR DESCRIPTION
**Pull request by knolleary**
Fixes #3778

Whilst all major browsers support Object.hasOwn, it is realistically a bit too new. We are getting too many issues with users on slightly out of date browsers - such as those included in LTS OS releases.

Given we only use it in one place, and is easily replaced, it is better to remove it than require browser upgrades.

### CODE REVIEW

**Review by Steve-Mcl — APPROVED** [review]
Yeah, I think hasOwn is a good thing but agree it we might be asking a bit much of users.
