### ISSUE TITLE
Nodered 3.1: evaluation of subflow environment variables failing

### ISSUE THREAD

**Issue by mbbrenner** [node-red/node-red#4342]
### Current Behavior

Since 3.1.0 MY_ENV_VARIABLE evaluates to " my friend" in all nodes using it within the subnode

### Expected Behavior

Until switching to 3.1.0 MY_ENV_VARIABLE evaluated to "Hello my friend" in all nodes using it within the subnode

### Steps To Reproduce

- create a subflow
- add a env variable of type string. e.g. MY_STRING_VARIABLE = "Hello"
- add a env variable of type $ env variable: e.g. MY_ENV_VARIABLE = "${MY_STRING_VARIABLE} my friend"
- use MY_ENV_VARIABLE for some further usage

### Example flow

```
[{"id":"75fec1c622cadd8d","type":"subflow","name":"Subflow 1","info":"","category":"","in":[{"x":340,"y":140,"wires":[{"id":"47ed696861ce39f6"}]}],"out":[{"x":720,"y":140,"wires":[{"id":"47ed696861ce39f6","port":0}]}],"env":[{"name":"MY_STRING_VARIABLE","type":"str","value":"Hello"},{"name":"MY_ENV_VARIABLE","type":"env","value":"${MY_STRING_VARIABLE} my friend"}],"meta":{},"color":"#DDAA99"},{"id":"47ed696861ce39f6","type":"change","z":"75fec1c622cadd8d","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"${MY_ENV_VARIABLE}","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":510,"y":140,"wires":[[]]},{"id":"95cbaba9b4497081","type":"debug","z":"aaa52f00.dafc7","name":"debug 42","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":3280,"y":740,"wires":[]},{"id":"95dee0cd6feb9e43","type":"subflow:75fec1c622cadd8d","z":"aaa52f00.dafc7","name":"","x":3020,"y":740,"wires":[["95cbaba9b4497081"]]},{"id":"1f7752563e2273e3","type":"inject","z":"aaa52f00.dafc7","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":2790,"y":740,"wires":[["95dee0cd6feb9e43"]]}]
```

### Environment

- Node-RED version: official Docker 3.1.0 
- Node.js version: as included in official image
- npm version: as included in official image
- Platform/OS: Synology NAS
- Browser: Safari

**Comment by knolleary** [comment]
Thanks for reporting @mbbrenner 

This is an area that received quite a large update in 3.1. Aside from the additional testing we did, I had hoped the beta period would help flush out any issues.

Thank you for providing a very clear issue report and an example flow to recreate - that'll make it much easier to track down.

**Comment by CERT-BA** [comment]
After updating from 3.0.2 to 3.1.0 my subflows don't work anymore, so I did some digging and I think it's the same problem but different.

### Example flow:
```
[{"id":"3d96d64979a93e6a","type":"subflow","name":"Subflow 1","info":"","category":"","in":[{"x":40,"y":40,"wires":[{"id":"48e2173ce2243534"}]}],"out":[],"env":[{"name":"test","type":"cred"}],"meta":{},"color":"#DDAA99"},{"id":"48e2173ce2243534","type":"debug","z":"3d96d64979a93e6a","name":"debug 10","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":160,"y":40,"wires":[]},{"id":"6ce2942bc0568d04","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"1f7752563e2273e3","type":"inject","z":"6ce2942bc0568d04","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":140,"y":40,"wires":[["6e70ba46abb68f3e"]]},{"id":"6e70ba46abb68f3e","type":"subflow:3d96d64979a93e6a","z":"6ce2942bc0568d04","name":"","x":280,"y":40,"wires":[]}]
```

The difference is not only that it doesn't work anymore, but also that the error messages are very strange:

```
"Error delivering message to node:undefined [undefined]"
```
```
TypeError: sendEvent.destination.node.receive is not a function
    at deliverMessageToDestination (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:799:40)
    at Immediate._onImmediate (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:815:21)
    at processImmediate (internal/timers.js:464:21)
```

Maybe this will help narrow down the error further.

If you think it's a different error I can create an new issue.

**Comment by knolleary** [comment]
@mbbrenner fixed via #4361 

@CERT-BA yours is an unrelated issue, albeit in a similar bit of code. Fixed via #4362
